version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: tq
    main: ./cmd/tq
    binary: tq
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  - id: tq
    ids: [ 'tq' ]
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
homebrew_casks:
  - name: tq
    ids: [ 'tq' ]
    homepage: https://github.com/jarxorg/tree#tq
    description: tq is a portable command-line JSON/YAML processor.
    repository:
      owner: jarxorg
      name: homebrew-tree
      token: "{{ .Env.TREE_HOMEBREW_TAP_GITHUB_TOKEN }}"
